"""
Django settings for CPMS project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from environs import Env
from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = Env()
env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3bo%j#oo@tfu+bj!n&l#5_3@f+r4n$=1nvv0%4(@l_u-g@2*b3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "corsheaders",

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_extensions',
    "managementsys.apps.ManagementsysConfig",
    "rest_framework",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'managementsys.discord_alerts.DiscordErrorAlertMiddleware',
    # Must sit last: it reads request.user in the response phase, which DRF only
    # populates once the view has authenticated.
    'managementsys.activity_log.ActivityLogMiddleware',
]

# Set False to stop the automatic per-request AuditLog rows. Explicit
# AuditLog.objects.create() calls in views/services are unaffected.
ACTIVITY_LOG_ENABLED = env.bool('ACTIVITY_LOG_ENABLED', True)

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_HEADERS = list(default_headers) + ["x-branch-id"]

ROOT_URLCONF = 'CPMS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CPMS.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env.str('DB_NAME', 'cpms'),
        'USER': env.str('DB_USER', 'postgres'),
        'PASSWORD': env.str('DB_PASSWORD', 'seesaw'),
        'HOST': env.str('DB_HOST', 'localhost'),
        'PORT': env.int('DB_PORT', 5432),
    },
    'external': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env.str('EXTERNAL_DB_NAME', 'ipos'),
        'USER': env.str('EXTERNAL_DB_USER', 'postgres'),
        'PASSWORD': env.str('EXTERNAL_DB_PASSWORD', 'seesaw'),
        'HOST': env.str('EXTERNAL_DB_HOST', 'localhost'),
        'PORT': env.int('EXTERNAL_DB_PORT', 5432),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Discord error alerts
# Leave DISCORD_WEBHOOK_URL empty to disable the feature entirely.
DISCORD_WEBHOOK_URL       = env.str('DISCORD_WEBHOOK_URL', '')
# Which response codes to report: comma-separated codes and/or ranges.
# '404,500-599' = 404s + all server errors. '400-599' = every client & server error.
DISCORD_ALERT_STATUSES    = env.str('DISCORD_ALERT_STATUSES', '404,500-599')
# Seconds to suppress repeats of the same status+method+path (0 = no throttling).
DISCORD_ALERT_COOLDOWN    = env.int('DISCORD_ALERT_COOLDOWN', 60)
# Shown in the embed footer — useful to tell dev from production.
DISCORD_ALERT_ENV_NAME    = env.str('DISCORD_ALERT_ENV_NAME', 'CPMS dev')
# Optional ping, e.g. '<@123456789>' or '@here'. Empty = silent embed.
DISCORD_ALERT_MENTION     = env.str('DISCORD_ALERT_MENTION', '')
# Include the JSON response body in the alert (off if bodies may hold patient data).
DISCORD_ALERT_INCLUDE_BODY = env.bool('DISCORD_ALERT_INCLUDE_BODY', True)
# Paths never reported (prefix match).
DISCORD_ALERT_IGNORE_PATHS = env.list('DISCORD_ALERT_IGNORE_PATHS', ['/favicon.ico', '/static/'])

# Vercel dashboard integration
CPMS_VERCEL_URL    = env.str('CPMS_VERCEL_URL', 'https://cpms-dashboard-api.vercel.app')
CPMS_INGEST_SECRET = env.str('CPMS_INGEST_SECRET', '')

# Online reservations (public booking form -> local queue).
# The public form books a slot, not a duration, so an imported appointment gets
# this length. Keep it equal to the slot_minutes setting on the Vercel admin
# page, or the schedule will show gaps and overlaps that do not exist.
CPMS_RESERVATION_DURATION_MINUTES = env.int('CPMS_RESERVATION_DURATION_MINUTES', 30)
# Which branch an online booking is filed under. Empty means null, which stays
# visible under every branch selection — see services/reservation_sync.py.
CPMS_RESERVATION_BRANCH_ID = env.int('CPMS_RESERVATION_BRANCH_ID', 0) or None

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'managementsys.auth_backend.AppUserAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'managementsys.auth_backend.IsAppAuthenticated',
    ],
}
