# Generated by Django 5.2.7 on 2026-04-13 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beauticians',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beautician_name', models.CharField(max_length=50)),
                ('bphone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_no', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='patientStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MedRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medrec_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('subjective', models.TextField(default='')),
                ('objective', models.TextField(default='')),
                ('assessment', models.TextField(default='')),
                ('plan', models.TextField(default='')),
                ('sabun_pagi', models.TextField(default='', null=True)),
                ('sabun_malam', models.TextField(default='', null=True)),
                ('toner_pagi', models.TextField(default='', null=True)),
                ('toner_malam', models.TextField(default='', null=True)),
                ('obat1_pagi', models.TextField(default='', null=True)),
                ('obat2_pagi', models.TextField(default='', null=True)),
                ('obat1_malam', models.TextField(default='', null=True)),
                ('obat2_malam', models.TextField(default='', null=True)),
                ('treatment', models.TextField(default='', null=True)),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='managementsys.doctors')),
                ('patient_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementsys.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ActivePatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('consult_status', models.BooleanField()),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
                ('patient_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementsys.patient')),
            ],
        ),
    ]
