# Generated by Django 5.2.7 on 2026-04-25 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0004_treatment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_time', models.DateTimeField(auto_now_add=True)),
                ('beautician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='managementsys.beauticians')),
                ('patient_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementsys.patient')),
                ('treatments', models.ManyToManyField(blank=True, to='managementsys.treatment')),
            ],
        ),
    ]
