# Generated by Django 5.2.7 on 2026-04-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0006_beauticians_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50)),
                ('pin_hash', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('admin', 'Admin')], default='admin', max_length=20)),
                ('avatar_color', models.CharField(default='#0284c7', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('auth_token', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
    ]
