# Generated by Django 5.2.7 on 2026-04-26 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0008_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activepatient',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='treatmentsession',
            name='active_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managementsys.activepatient'),
        ),
        migrations.AlterField(
            model_name='activepatient',
            name='patient_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managementsys.patient'),
        ),
        migrations.AlterField(
            model_name='treatmentsession',
            name='patient_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managementsys.patient'),
        ),
    ]
