# Generated by Django 5.2.7 on 2026-04-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0009_activepatient_guest_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoapTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('subjective', 'Subjective'), ('objective', 'Objective'), ('assessment', 'Assessment'), ('plan', 'Plan')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['field', 'sort_order', 'title'],
            },
        ),
    ]
