# Generated by Django 5.2.7 on 2026-05-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0011_warehouse_inventoryitem_inventorybatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('cogs', 'Cost of Goods Sold'), ('expense', 'Expense'), ('other_income', 'Other Income'), ('other_expense', 'Other Expense')], max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Chart of Account',
                'verbose_name_plural': 'Chart of Accounts',
                'ordering': ['account_number'],
            },
        ),
    ]
