# Generated by Django 5.2.7 on 2026-05-02 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0014_patientphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='activepatient',
            name='medrec',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_visit', to='managementsys.medrec'),
        ),
    ]
