# Generated by Django 5.2.7 on 2026-05-03 11:27

from django.db import migrations, models


def rename_admin_to_superuser(apps, schema_editor):
    AppUser = apps.get_model('managementsys', 'AppUser')
    AppUser.objects.filter(role='admin').update(role='superuser')


def rename_superuser_to_admin(apps, schema_editor):
    AppUser = apps.get_model('managementsys', 'AppUser')
    AppUser.objects.filter(role='superuser').update(role='admin')


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0016_invoice_invoiceitem'),
    ]

    operations = [
        migrations.RunPython(rename_admin_to_superuser, reverse_code=rename_superuser_to_admin),
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('doctor', 'Doctor'), ('beautician', 'Beautician')], default='superuser', max_length=20),
        ),
    ]
