# Generated by Django 5.2.7 on 2026-05-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0022_patientnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='medrec',
            name='assessment_codes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
