# Generated by Django 5.2.7 on 2026-05-10 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0023_assessmentcode_medrec_assessment_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('min_visit_count', models.IntegerField(default=0)),
                ('min_total_spend', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('color_hex', models.CharField(default='#6b7280', max_length=7)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PatientCRMProfile',
            fields=[
                ('patient_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='crm_profile', serialize=False, to='managementsys.patient')),
                ('total_spend', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_visits', models.IntegerField(default=0)),
                ('last_visit_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managementsys.patienttier')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('scope', models.CharField(choices=[('all', 'All'), ('category', 'Treatment Category'), ('item', 'Specific Item')], default='all', max_length=10)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('max_uses', models.IntegerField(blank=True, null=True)),
                ('max_uses_per_patient', models.IntegerField(default=0)),
                ('is_auto', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicable_categories', models.ManyToManyField(blank=True, to='managementsys.treatmentcategory')),
                ('applicable_items', models.ManyToManyField(blank=True, to='managementsys.inventoryitem')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managementsys.appuser')),
                ('min_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='managementsys.patienttier')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='managementsys.promotion'),
        ),
        migrations.CreateModel(
            name='PromotionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_applied', models.DecimalField(decimal_places=2, max_digits=14)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_usage', to='managementsys.invoice')),
                ('patient_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_usages', to='managementsys.patient')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='managementsys.promotion')),
            ],
        ),
    ]
