# Generated by Django 5.2.7 on 2026-05-10 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0024_patienttier_patientcrmprofile_promotion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('expected_start', models.TimeField()),
                ('expected_end', models.TimeField()),
                ('color_hex', models.CharField(default='#0284c7', max_length=7)),
            ],
            options={
                'ordering': ['expected_start'],
            },
        ),
        migrations.AddField(
            model_name='appuser',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clock_in', models.DateTimeField(blank=True, null=True)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('day_off', 'Day Off')], default='absent', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='managementsys.appuser')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('staff', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StaffSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='managementsys.appuser')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managementsys.workshift')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
