# Generated by Django 5.2.7 on 2026-05-11 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0025_workshift_appuser_base_salary_attendancerecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'asset'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='managementsys.chartofaccounts'),
        ),
    ]
