# Generated by Django 5.2.7 on 2026-05-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0027_assessmentcode_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='legal_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('doctor', 'Doctor'), ('beautician', 'Beautician'), ('cashier', 'Cashier')], default='superuser', max_length=20),
        ),
    ]
