# Generated by Django 5.2.7 on 2026-05-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0028_add_category_legal_code_to_inventoryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='code',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
