# Generated by Django 5.2.7 on 2026-05-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0029_increase_inventoryitem_code_name_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='theme_background',
            field=models.CharField(default='#f1f5f9', max_length=7),
        ),
        migrations.AddField(
            model_name='appuser',
            name='theme_primary',
            field=models.CharField(default='#0284c7', max_length=7),
        ),
        migrations.AddField(
            model_name='appuser',
            name='theme_secondary',
            field=models.CharField(default='#7c3aed', max_length=7),
        ),
    ]
