# Generated by Django 5.2.7 on 2026-05-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0032_invoice_notes_promotion_code_invoiceitem_discount_pct_item_name_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='code',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
