# Generated by Django 5.2.7 on 2026-05-26 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0033_increase_treatment_code_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='catalog_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treatment', to='managementsys.inventoryitem'),
        ),
    ]
