# Generated by Django 5.2.7 on 2026-05-27 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0034_protect_treatment_catalog_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('exhausted', 'Exhausted')], default='active', max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='managementsys.patient')),
                ('purchased_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages_sold', to='managementsys.invoice')),
            ],
            options={
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientPackageRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_redemptions', to='managementsys.invoice')),
                ('patient_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='managementsys.patientpackage')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_redemptions', to='managementsys.treatment')),
            ],
            options={
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('catalog_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treatment_package', to='managementsys.inventoryitem')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='patientpackage',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_packages', to='managementsys.treatmentpackage'),
        ),
        migrations.CreateModel(
            name='TreatmentPackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions', models.PositiveIntegerField(default=1)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='managementsys.treatmentpackage')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_items', to='managementsys.treatment')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('package', 'treatment')},
            },
        ),
    ]
