# Generated by Django 5.2.7 on 2026-05-28 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0035_patientpackage_patientpackageredemption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccounts',
            name='is_head',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_head': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_accounts', to='managementsys.chartofaccounts'),
        ),
    ]
