# Generated by Django 5.2.7 on 2026-06-02 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0036_patient_updated_at'),
        ('managementsys', '0038_cash_head_promote'),
    ]

    operations = [
    ]
