# Generated by Django 5.2.7 on 2026-06-03 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0039_merge_0036_patient_updated_at_0038_cash_head_promote'),
        ('managementsys', '0039_siteconfig'),
    ]

    operations = [
    ]
