# Generated by Django 5.2.7 on 2026-06-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0041_add_issue_ticket_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('doctor', 'Doctor'), ('beautician', 'Beautician'), ('cashier', 'Cashier'), ('manager', 'Manager')], default='superuser', max_length=20),
        ),
    ]
