# Generated by Django 5.2.7 on 2026-06-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0042_alter_appuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueticket',
            name='category',
            field=models.CharField(choices=[('sistem', 'Sistem'), ('peralatan', 'Peralatan'), ('jaringan', 'Jaringan'), ('produk', 'Produk')], default='sistem', max_length=20),
        ),
    ]
