# Generated by Django 5.2.7 on 2026-06-04 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0048_ledgerentry'),
        ('managementsys', '0048_treatmentmaterial'),
    ]

    operations = [
    ]
