# Generated by Django 5.2.7 on 2026-06-04 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0049_batch_quantity_decimal'),
        ('managementsys', '0049_merge_0048_ledgerentry_0048_treatmentmaterial'),
    ]

    operations = [
    ]
