# Generated by Django 5.2.7 on 2026-06-17 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0057_sort_order_treatment_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('output_quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes_created', to='managementsys.appuser')),
                ('output_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes_as_output', to='managementsys.inventoryitem')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('output_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='managementsys.inventoryitem')),
                ('output_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='managementsys.warehouse')),
                ('produced_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_runs', to='managementsys.inventorybatch')),
                ('produced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_runs', to='managementsys.appuser')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='managementsys.productionrecipe')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionRunIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_small', models.DecimalField(decimal_places=4, max_digits=14)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_consumed_lines', to='managementsys.inventoryitem')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='managementsys.productionrun')),
                ('source_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_consumed_lines', to='managementsys.warehouse')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionRecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='small', max_length=10)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_ingredient_lines', to='managementsys.inventoryitem')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='managementsys.productionrecipe')),
            ],
            options={
                'ordering': ['ordering', 'id'],
                'unique_together': {('recipe', 'item')},
            },
        ),
    ]
