# Generated by Django 5.2.7 on 2026-06-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0059_colorpalette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorpalette',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
