# Generated by Django 5.2.7 on 2026-06-17 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0060_alter_colorpalette_id'),
        ('managementsys', '0060_refresh_palettes'),
    ]

    operations = [
    ]
