# Generated by Django 5.2.7 on 2026-06-17 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0061_add_crimson_palette'),
        ('managementsys', '0061_merge_20260618_0228'),
    ]

    operations = [
    ]
