# Generated by Django 5.2.7 on 2026-07-17 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0066_invoice_purchaseinvoice_void_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_code', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('ihs_id', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='doctors',
            name='ihs_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='nik',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='ihs_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_no', models.CharField(blank=True, max_length=20, unique=True)),
                ('guest_name', models.CharField(blank=True, max_length=100, null=True)),
                ('service_category', models.CharField(blank=True, max_length=100)),
                ('service_type', models.CharField(blank=True, max_length=100)),
                ('appointment_type', models.CharField(blank=True, choices=[('routine', 'Routine'), ('follow_up', 'Follow Up'), ('walk_in', 'Walk In')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('pending', 'Pending'), ('booked', 'Booked'), ('arrived', 'Arrived'), ('checked-in', 'Checked In'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled'), ('noshow', 'No Show'), ('waitlist', 'Waitlist'), ('entered-in-error', 'Entered In Error')], default='booked', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ihs_appointment_id', models.CharField(blank=True, max_length=64, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('not_synced', 'Not Synced'), ('synced', 'Synced'), ('error', 'Error')], default='not_synced', max_length=20)),
                ('sync_error', models.TextField(blank=True)),
                ('linked_active_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_appointments', to='managementsys.activepatient')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='managementsys.patient')),
                ('practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='managementsys.doctors')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='managementsys.appointmentlocation')),
            ],
            options={
                'ordering': ['start_at'],
                'indexes': [models.Index(fields=['start_at', 'status'], name='managements_start_a_1d5090_idx')],
            },
        ),
    ]
