# Generated by Django 5.2.7 on 2026-08-03 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0082_finalize_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttransfer',
            name='posting_status',
            field=models.CharField(choices=[('unposted', 'Unposted'), ('posted', 'Posted')], default='unposted', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='posting_status',
            field=models.CharField(choices=[('unposted', 'Unposted'), ('posted', 'Posted')], default='unposted', max_length=10),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='posting_status',
            field=models.CharField(choices=[('unposted', 'Unposted'), ('posted', 'Posted')], default='unposted', max_length=10),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='source_type',
            field=models.CharField(blank=True, choices=[('invoice', 'Sales Invoice'), ('purchase', 'Purchase Invoice'), ('transfer', 'Account Transfer'), ('adjustment', 'Manual Adjustment'), ('stock', 'Stock Movement'), ('opname', 'Stock Opname'), ('manual', 'Manual Entry'), ('void_memo', 'Void Memo (reversal)'), ('edit_memo', 'Edit Memo (reversal + repost)')], default='', max_length=15),
        ),
        # NOTE: a `PaymentMethod.id` AlterField (AutoField -> BigAutoField) was
        # generated here by makemigrations too. It's pre-existing drift from
        # Phase 1 unrelated to Phase 2 (DEFAULT_AUTO_FIELD='BigAutoField' vs.
        # the AutoField baked into migration 0080) — left out of this
        # migration on purpose so this file only does what its name says.
        migrations.CreateModel(
            name='JournalBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_range_start', models.DateField()),
                ('requested_range_end', models.DateField()),
                ('swept_range_start', models.DateField(blank=True, null=True)),
                ('swept_range_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_batches', to='managementsys.appuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalDayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('is_posted', models.BooleanField(default=False)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_count', models.IntegerField(default=0)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_logs', to='managementsys.journalbatch')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_day_logs', to='managementsys.appuser')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
