# Generated by Django 5.2.7 on 2026-08-06 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0095_drop_category_cogs_expense_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntrySequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('last_number', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(max_length=24, unique=True)),
                ('date', models.DateField(db_index=True)),
                ('memo', models.CharField(blank=True, default='', max_length=255)),
                ('source_type', models.CharField(blank=True, choices=[('invoice', 'Sales Invoice'), ('purchase', 'Purchase Invoice'), ('transfer', 'Account Transfer'), ('adjustment', 'Manual Adjustment'), ('stock', 'Stock Movement'), ('opname', 'Stock Opname'), ('manual', 'Manual Entry'), ('void_memo', 'Void Memo (reversal)'), ('edit_memo', 'Edit Memo (reversal + repost)'), ('expense', 'Expense'), ('reversal', 'Reversal'), ('correction', 'Correction')], default='', max_length=15)),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('is_balanced', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='managementsys.journalbatch')),
                ('corrects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='managementsys.journalentry')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='managementsys.appuser')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='managementsys.expense')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='managementsys.invoice')),
                ('purchase_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='managementsys.purchaseinvoice')),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='managementsys.journalentry')),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='managementsys.accounttransfer')),
            ],
            options={
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='managementsys.journalentry'),
        ),
        migrations.CreateModel(
            name='JournalStagingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_to', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('committing', 'Committing'), ('committed', 'Committed'), ('discarded', 'Discarded'), ('failed', 'Failed')], default='draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('entry_count', models.IntegerField(default=0)),
                ('document_count', models.IntegerField(default=0)),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('days_committed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('variance_notes', models.JSONField(blank=True, default=list)),
                ('committed_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staging_batches', to='managementsys.journalbatch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_staging_batches', to='managementsys.appuser')),
            ],
            options={
                'verbose_name_plural': 'Journal Staging Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StagedJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('sequence', models.IntegerField(default=0)),
                ('source_type', models.CharField(max_length=15)),
                ('source_model', models.CharField(max_length=32)),
                ('source_id', models.IntegerField()),
                ('source_label', models.CharField(blank=True, default='', max_length=120)),
                ('memo', models.CharField(blank=True, default='', max_length=255)),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('is_balanced', models.BooleanField(default=True)),
                ('has_estimate', models.BooleanField(default=False)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('source_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='managementsys.journalstagingbatch')),
            ],
            options={
                'verbose_name_plural': 'Staged Journal Entries',
                'ordering': ['date', 'sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StagedJournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_account_label', models.CharField(blank=True, default='', max_length=120)),
                ('entry_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('description', models.CharField(max_length=255)),
                ('is_estimated', models.BooleanField(default=False)),
                ('sequence', models.IntegerField(default=0)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staged_journal_lines', to='managementsys.chartofaccounts')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='managementsys.stagedjournalentry')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['date', 'source_type'], name='managements_date_da3e06_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['batch'], name='managements_batch_i_8ed60d_idx'),
        ),
        migrations.AddIndex(
            model_name='stagedjournalentry',
            index=models.Index(fields=['batch', 'date'], name='managements_batch_i_246eeb_idx'),
        ),
        migrations.AddIndex(
            model_name='stagedjournalentry',
            index=models.Index(fields=['batch', 'source_type'], name='managements_batch_i_847181_idx'),
        ),
    ]
