# Generated by Django 5.2.7 on 2026-08-07 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0097_backfill_journal_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='payment_account',
            field=models.ForeignKey(blank=True, help_text='Cash/bank account the invoice was last settled from. Must be one of services.cash_accounts.cash_bank_account_ids().', limit_choices_to={'account_type': 'asset'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices_paid_from', to='managementsys.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='payment_account',
            field=models.ForeignKey(blank=True, help_text='Cash/bank account credited by this payment. Must be one of services.cash_accounts.cash_bank_account_ids().', limit_choices_to={'account_type': 'asset'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_payments_from', to='managementsys.chartofaccounts'),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_payments', to='managementsys.paymentmethod'),
        ),
    ]
