# Generated by Django 5.2.7 on 2026-08-11 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0102_backfill_invoice_payment_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sort_order', models.IntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='managementsys.invoice')),
                ('payment_account', models.ForeignKey(blank=True, help_text='Cash/bank account debited by this tender. Must be one of services.cash_accounts.cash_bank_account_ids().', limit_choices_to={'account_type': 'asset'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_payments_into', to='managementsys.chartofaccounts')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_payments', to='managementsys.paymentmethod')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
