# Generated by Django 5.2.7 on 2026-08-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0103_invoicepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(blank=True, choices=[('invoice', 'Sales Invoice'), ('purchase', 'Purchase Invoice'), ('transfer', 'Account Transfer'), ('adjustment', 'Manual Adjustment'), ('stock', 'Stock Movement'), ('opname', 'Stock Opname'), ('manual', 'Manual Entry'), ('void_memo', 'Void Memo (reversal)'), ('edit_memo', 'Edit Memo (reversal + repost)'), ('restore_memo', 'Restore Memo (un-void repost)'), ('expense', 'Expense'), ('reversal', 'Reversal'), ('correction', 'Correction')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='source_type',
            field=models.CharField(blank=True, choices=[('invoice', 'Sales Invoice'), ('purchase', 'Purchase Invoice'), ('transfer', 'Account Transfer'), ('adjustment', 'Manual Adjustment'), ('stock', 'Stock Movement'), ('opname', 'Stock Opname'), ('manual', 'Manual Entry'), ('void_memo', 'Void Memo (reversal)'), ('edit_memo', 'Edit Memo (reversal + repost)'), ('restore_memo', 'Restore Memo (un-void repost)'), ('expense', 'Expense')], default='', max_length=15),
        ),
    ]
