# Generated by Django 5.2.7 on 2026-08-18 13:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0107_remove_treatmentmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('basis', models.CharField(choices=[('period', 'Periode Terpilih'), ('ytd', 'Akumulasi Tahun Berjalan')], default='period', max_length=10)),
                ('rate_mode', models.CharField(choices=[('flat', 'Tarif Tunggal'), ('bracket', 'Tarif Progresif'), ('facility', 'Tarif Fasilitas (Pasal 31E)'), ('none', 'Tanpa Tarif')], default='flat', max_length=10)),
                ('rate_percent', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('facility_turnover_cap', models.DecimalField(decimal_places=2, default=0, help_text='Batas peredaran bruto yang mendapat fasilitas (Rp 4,8 M).', max_digits=18)),
                ('facility_full_rate_cap', models.DecimalField(decimal_places=2, default=0, help_text='Di atas batas ini fasilitas hilang sepenuhnya (Rp 50 M).', max_digits=18)),
                ('facility_factor', models.DecimalField(decimal_places=4, default=Decimal('0.5'), help_text='Pengali tarif untuk bagian yang mendapat fasilitas.', max_digits=5)),
                ('rounding', models.CharField(choices=[('none', 'Tanpa Pembulatan'), ('rupiah', 'Bulat Rupiah (ke bawah)'), ('thousand', 'Bulat Ribuan (ke bawah)')], default='rupiah', max_length=10)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility_turnover_rule', models.ForeignKey(blank=True, help_text='Aturan yang menyediakan angka peredaran bruto untuk diuji.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_dependents', to='managementsys.taxrule')),
            ],
            options={
                'verbose_name': 'Tax Rule',
                'verbose_name_plural': 'Tax Rules',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TaxRuleBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_bound', models.DecimalField(blank=True, decimal_places=2, help_text='Batas atas lapisan; kosongkan untuk lapisan terakhir.', max_digits=18, null=True)),
                ('rate_percent', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('display_order', models.IntegerField(default=0)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='managementsys.taxrule')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaxRuleComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('account', 'Akun'), ('subtree', 'Akun & Turunannya'), ('type', 'Jenis Akun'), ('rule', 'Hasil Aturan Lain'), ('fixed', 'Nilai Tetap')], default='account', max_length=10)),
                ('sign', models.SmallIntegerField(default=1)),
                ('account_type', models.CharField(blank=True, default='', max_length=20)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('display_order', models.IntegerField(default=0)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_components', to='managementsys.chartofaccounts')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='managementsys.taxrule')),
                ('source_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referenced_by', to='managementsys.taxrule')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
