"""Patient birthday + gender, and the CRM WhatsApp message template store.

WHY birth_date / gender
-----------------------
Neither existed. The CRM page needs the birthday to drive a greeting list and
the two together to segment the book by age and gender, and there was nowhere
to put either — reception has been recording them on paper.

Both are nullable and every existing row gets NULL/blank. That is not a defect
to be backfilled from NIK: the Indonesian NIK does encode a birth date (and
sex, via +40 on the day for women), but a meaningful share of the stored NIK
values are short, padded, or transcribed wrong, and a silently derived birthday
that greets a patient on the wrong day is worse than an empty field. Reception
fills these in on the next visit, and every statistic that reads them reports
its own coverage so partial data cannot be mistaken for a finding.

WHY MessageTemplate
-------------------
Follow-up WhatsApp text the operator copies by hand. It is a shared store rather
than browser state so the wording is the same whoever is on the front desk. It
sends nothing and is wired to no messaging API — a template row is text with
{placeholder} tokens, substituted on read by services/message_templates.py.
"""
# Generated by Django 5.2.7 on 2026-08-19 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0109_operational_input_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Perempuan'), ('M', 'Laki-laki')], default='', max_length=1),
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('followup', 'Follow-up Kunjungan'), ('birthday', 'Ulang Tahun'), ('reminder', 'Pengingat Jadwal'), ('promo', 'Promosi'), ('other', 'Lainnya')], default='followup', max_length=20)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_templates', to='managementsys.appuser')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
