"""WhatsApp opt-in on Patient, plus the OpenWA gateway settings and blast log.

WHY wa_opt_in DEFAULTS TO FALSE
-------------------------------
Every patient already on file gets False. That is the point, not an oversight to
be backfilled: consent the patient never gave is not consent, and a default of
True would silently enrol the whole book in a broadcast list on the day this
migration runs. Reception turns it on per patient as they agree, so the blast
audiences start at zero and grow. The blast page reports "N match, M opted in"
so the gap is visible rather than surprising.

Consent is only ever changed through /api/patients/<no>/wa-opt-in/, which writes
an AuditLog row. The field is read-only on PatientSerializer so a stale admin
form cannot flip it back as a side effect of an unrelated edit.

WHAT THE OTHER THREE MODELS ARE
-------------------------------
WhatsAppSettings   singleton: which OpenWA gateway to talk to, the send pacing,
                   and the guard rails (daily cap, per-patient cooldown, quiet
                   hours). The api_key is stored plain because the gateway needs
                   the literal value; it is never serialized back to the browser.
WhatsAppBlast      one broadcast — audience, message snapshot, gateway batch id.
WhatsAppBlastRecipient
                   one row per recipient, written *before* dispatch so a run
                   that dies half way still records who was already contacted.
                   That record is what the per-patient cooldown reads.

The gateway (github.com/rmyndharis/OpenWA) is a separate Node service. Nothing
in Django talks to WhatsApp directly, and no message is ever sent by a signal,
a save hook, or a scheduled job — only by an operator pressing send.
"""
# Generated by Django 5.2.7 on 2026-08-19 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0110_patient_birth_date_patient_gender_messagetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='wa_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='wa_opt_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WhatsAppBlast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('segment', models.CharField(max_length=40)),
                ('segment_params', models.JSONField(blank=True, default=dict)),
                ('body_snapshot', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('processing', 'Berjalan'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan'), ('failed', 'Gagal')], default='pending', max_length=20)),
                ('batch_id', models.CharField(blank=True, default='', max_length=100)),
                ('total', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_blasts', to='managementsys.appuser')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blasts', to='managementsys.messagetemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppBlastRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(blank=True, default='', max_length=100)),
                ('chat_id', models.CharField(max_length=40)),
                ('phone', models.CharField(blank=True, default='', max_length=25)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('sent', 'Terkirim'), ('failed', 'Gagal'), ('cancelled', 'Dibatalkan')], default='pending', max_length=20)),
                ('batch_id', models.CharField(blank=True, default='', max_length=100)),
                ('message_id', models.CharField(blank=True, default='', max_length=120)),
                ('error_code', models.CharField(blank=True, default='', max_length=60)),
                ('error', models.CharField(blank=True, default='', max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('blast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='managementsys.whatsappblast')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='managementsys.patient')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('base_url', models.URLField(blank=True, default='http://127.0.0.1:2785', max_length=255)),
                ('api_key', models.CharField(blank=True, default='', max_length=255)),
                ('session_id', models.CharField(blank=True, default='', max_length=64)),
                ('session_name', models.CharField(blank=True, default='cpms-clinic', max_length=50)),
                ('delay_between_messages_ms', models.PositiveIntegerField(default=8000)),
                ('randomize_delay', models.BooleanField(default=True)),
                ('daily_send_cap', models.PositiveIntegerField(default=200)),
                ('per_patient_cooldown_days', models.PositiveIntegerField(default=7)),
                ('quiet_hours_start', models.PositiveSmallIntegerField(default=21)),
                ('quiet_hours_end', models.PositiveSmallIntegerField(default=8)),
                ('test_recipient', models.CharField(blank=True, default='', max_length=25)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_settings_updates', to='managementsys.appuser')),
            ],
            options={
                'verbose_name': 'WhatsApp Settings',
            },
        ),
        migrations.AddIndex(
            model_name='whatsappblast',
            index=models.Index(fields=['-created_at'], name='idx_wablast_created'),
        ),
        migrations.AddIndex(
            model_name='whatsappblastrecipient',
            index=models.Index(fields=['patient', 'sent_at'], name='idx_warecipient_patient'),
        ),
    ]
