# Generated by Django 5.2.7 on 2026-08-22 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0113_seed_default_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(blank=True, choices=[('invoice', 'Sales Invoice'), ('purchase', 'Purchase Invoice'), ('transfer', 'Account Transfer'), ('adjustment', 'Manual Adjustment'), ('stock', 'Stock Movement'), ('opname', 'Stock Opname'), ('manual', 'Manual Entry'), ('void_memo', 'Void Memo (reversal)'), ('edit_memo', 'Edit Memo (reversal + repost)'), ('restore_memo', 'Restore Memo (un-void repost)'), ('expense', 'Expense'), ('sales_return', 'Sales Return'), ('reversal', 'Reversal'), ('correction', 'Correction')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='source_type',
            field=models.CharField(blank=True, choices=[('invoice', 'Sales Invoice'), ('purchase', 'Purchase Invoice'), ('transfer', 'Account Transfer'), ('adjustment', 'Manual Adjustment'), ('stock', 'Stock Movement'), ('opname', 'Stock Opname'), ('manual', 'Manual Entry'), ('void_memo', 'Void Memo (reversal)'), ('edit_memo', 'Edit Memo (reversal + repost)'), ('restore_memo', 'Restore Memo (un-void repost)'), ('expense', 'Expense'), ('sales_return', 'Sales Return')], default='', max_length=15),
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('datetime', models.DateTimeField()),
                ('reason', models.CharField(choices=[('customer_change', 'Pelanggan Berubah Pikiran'), ('wrong_item', 'Barang Salah'), ('damaged', 'Barang Rusak'), ('expired', 'Kedaluwarsa'), ('other', 'Lainnya')], default='customer_change', max_length=20)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('total_refund', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_voided', models.BooleanField(default=False)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('posting_status', models.CharField(choices=[('unposted', 'Unposted'), ('posted', 'Posted')], default='unposted', max_length=10)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_returns', to='managementsys.branch')),
                ('invoice', models.ForeignKey(help_text='The sale being returned against. PROTECT: an invoice with a return on it is history that must stay resolvable.', on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='managementsys.invoice')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_returns_processed', to='managementsys.appuser')),
                ('refund_account', models.ForeignKey(blank=True, help_text='Cash/bank account credited by this refund. Must be one of services.cash_accounts.cash_bank_account_ids().', limit_choices_to={'account_type': 'asset'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_returns_paid_from', to='managementsys.chartofaccounts')),
                ('refund_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_returns', to='managementsys.paymentmethod')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_sales_returns', to='managementsys.appuser')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_returns', to='managementsys.warehouse')),
            ],
            options={
                'verbose_name': 'Sales Return',
                'ordering': ['-datetime', '-id'],
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='sales_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='managementsys.salesreturn'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='sales_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='managementsys.salesreturn'),
        ),
        migrations.CreateModel(
            name='SalesReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('restock', models.BooleanField(default=True)),
                ('cogs_reversed', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='managementsys.invoiceitem')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='managementsys.inventoryitem')),
                ('sales_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='managementsys.salesreturn')),
            ],
            options={
                'verbose_name': 'Sales Return Item',
                'ordering': ['id'],
            },
        ),
    ]
