# Generated by Django 5.2.7 on 2026-08-22 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0114_alter_journalentry_source_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_start', models.DateField()),
                ('statement_end', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Selesai')], default='draft', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(help_text='The cash/bank account being reconciled. Must be one of services.cash_accounts.cash_bank_account_ids().', limit_choices_to={'account_type': 'asset'}, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='managementsys.chartofaccounts')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='managementsys.branch')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations_completed', to='managementsys.appuser')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations_created', to='managementsys.appuser')),
            ],
            options={
                'verbose_name': 'Bank Reconciliation',
                'ordering': ['-statement_end', '-id'],
            },
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='reconciliation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_entries', to='managementsys.bankreconciliation'),
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('match_type', models.CharField(blank=True, choices=[('auto', 'Otomatis'), ('manual', 'Manual')], default='', max_length=10)),
                ('is_ignored', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement_lines', to='managementsys.ledgerentry')),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='managementsys.bankreconciliation')),
            ],
            options={
                'verbose_name': 'Bank Statement Line',
                'ordering': ['date', 'sort_order', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ledger_entry__isnull', False)), fields=('reconciliation', 'ledger_entry'), name='uniq_ledger_entry_per_reconciliation')],
            },
        ),
    ]
