# Generated by Django 5.2.7 on 2026-08-23 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0115_bankreconciliation_ledgerentry_reconciliation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='source',
            field=models.CharField(choices=[('staff', 'Staff'), ('online', 'Online Reservation')], default='staff', max_length=20),
        ),
        migrations.CreateModel(
            name='ReservationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('reserved_at', models.DateTimeField()),
                ('service_name', models.CharField(blank=True, max_length=100)),
                ('service_id', models.PositiveIntegerField(blank=True, null=True)),
                ('match_status', models.CharField(choices=[('matched', 'Matched'), ('unmatched', 'No Matching Patient'), ('ambiguous', 'Multiple Matching Patients'), ('invalid_phone', 'Unusable Phone Number')], default='unmatched', max_length=20)),
                ('candidate_patient_nos', models.JSONField(blank=True, default=list)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('pulled_at', models.DateTimeField(auto_now_add=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_reservations', to='managementsys.appuser')),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_request', to='managementsys.appointment')),
                ('matched_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_requests', to='managementsys.patient')),
            ],
            options={
                'ordering': ['-reserved_at'],
                'indexes': [models.Index(fields=['acknowledged_at', 'reserved_at'], name='managements_acknowl_5ec887_idx'), models.Index(fields=['match_status'], name='managements_match_s_6012a0_idx')],
            },
        ),
    ]
