# Generated by Django 5.2.7 on 2026-08-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0116_appointment_contact_phone_appointment_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalstagingbatch',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
    ]
