# Generated by Django 5.2.7 on 2026-08-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0117_journalstagingbatch_date_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='duration_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='method',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='source',
            field=models.CharField(choices=[('app', 'Application'), ('http', 'HTTP request')], default='app', max_length=10),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-timestamp'], name='managements_timesta_21a5cc_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity_type', '-timestamp'], name='managements_entity__13273e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-timestamp'], name='managements_action_12e96d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['source', '-timestamp'], name='managements_source_70aafc_idx'),
        ),
    ]
