# Generated by Django 5.2.7 on 2026-09-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsys', '0118_auditlog_duration_ms_auditlog_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='posting_status',
            field=models.CharField(choices=[('unposted', 'Unposted'), ('posted', 'Posted'), ('excluded', 'Excluded from journal')], default='unposted', max_length=10),
        ),
    ]
