"""
seed_tax_rules
==============
Creates the starting set of Indonesian tax rules for /accounting/tax.
Idempotent — a rule that already exists is left alone unless --overwrite is
given, so an operator's edits are never silently reverted.

The rules seeded here are a *starting point sized to this clinic*, not tax
advice. Two of them deliberately need a human decision before they mean
anything:

  ppn_keluaran   Health services are largely VAT-exempt while retail product
                 sales are not, so the base is seeded as product revenue only.
                 If the clinic is not a PKP, deactivate the PPN rules entirely.
  ppn_masukan    Input VAT comes off supplier tax invoices, which the ledger
                 does not model yet. Seeded with no base at all — it computes
                 zero and visibly asks to be pointed at an account.

Rates and thresholds are stored as data. When a rate changes, edit the rule on
the page (or add a replacement with effective_from set); do not edit this file
and re-seed.

Usage:
    python manage.py seed_tax_rules
    python manage.py seed_tax_rules --overwrite
    python manage.py seed_tax_rules --dry-run
"""
from decimal import Decimal

from django.core.management.base import BaseCommand
from django.db import transaction

from managementsys.models import (
    ChartOfAccounts, TaxRule, TaxRuleBracket, TaxRuleComponent,
)

M = Decimal('1000000')

# PTKP TK/0 — the single-no-dependants allowance. A clinic with real payroll
# should split PPh 21 per employee status; this is the conservative default.
PTKP_TK0 = Decimal('54000000')

# Progressive layers, UU HPP (UU 7/2021) Pasal 17.
PPH21_BRACKETS = [
    (Decimal('60000000'),   Decimal('5')),
    (Decimal('250000000'),  Decimal('15')),
    (Decimal('500000000'),  Decimal('25')),
    (Decimal('5000000000'), Decimal('30')),
    (None,                  Decimal('35')),
]

# Salary-ish expense accounts that form the PPh 21 base.
PPH21_ACCOUNTS = [6400010, 6400020, 6400040]


def _rule(code, **kwargs):
    return dict(code=code, **kwargs)


RULES = [
    _rule(
        'peredaran_bruto',
        name='Peredaran Bruto (Omzet)',
        description='Total pendapatan setahun berjalan. Dasar uji ambang '
                    'Rp 4,8 M dan fasilitas Pasal 31E.',
        basis='ytd', rate_mode='none', rounding='rupiah', display_order=10,
        components=[{'source': 'type', 'account_type': 'revenue', 'sign': 1,
                     'label': 'Seluruh akun pendapatan'}],
        notes='Diskon penjualan (4100000) otomatis mengurangi omzet karena '
              'bersaldo debit di dalam kelompok pendapatan.',
    ),
    _rule(
        'pph_final_umkm',
        name='PPh Final UMKM 0,5% (PP 55/2022)',
        description='0,5% dari peredaran bruto periode berjalan. Hanya berlaku '
                    'bila omzet setahun di bawah Rp 4,8 M.',
        basis='period', rate_mode='flat', rate_percent=Decimal('0.5'),
        rounding='rupiah', display_order=20,
        components=[{'source': 'type', 'account_type': 'revenue', 'sign': 1,
                     'label': 'Peredaran bruto periode ini'}],
        notes='Nonaktifkan aturan ini bila klinik memilih tarif umum '
              '(pembukuan) alih-alih PPh final.',
    ),
    _rule(
        'laba_kena_pajak',
        name='Penghasilan Kena Pajak',
        description='Laba bersih komersial setahun berjalan, sebelum koreksi fiskal.',
        basis='ytd', rate_mode='none', rounding='rupiah', display_order=30,
        components=[
            {'source': 'type', 'account_type': 'revenue',       'sign': 1,  'label': 'Pendapatan'},
            {'source': 'type', 'account_type': 'cogs',          'sign': -1, 'label': 'Harga pokok penjualan'},
            {'source': 'type', 'account_type': 'expense',       'sign': -1, 'label': 'Beban operasional'},
            {'source': 'type', 'account_type': 'other_income',  'sign': 1,  'label': 'Pendapatan lain-lain'},
            {'source': 'type', 'account_type': 'other_expense', 'sign': -1, 'label': 'Beban lain-lain'},
        ],
        notes='Angka ini laba komersial. Koreksi fiskal (beban tidak boleh '
              'dikurangkan, penyusutan fiskal) belum diperhitungkan — tambahkan '
              'sebagai komponen Nilai Tetap bila diperlukan.',
    ),
    _rule(
        'pph_badan',
        name='PPh Badan 22% (dengan fasilitas Pasal 31E)',
        description='22% dari penghasilan kena pajak. Bagian yang sebanding '
                    'dengan omzet Rp 4,8 M pertama mendapat potongan 50%.',
        basis='ytd', rate_mode='facility', rate_percent=Decimal('22'),
        rounding='rupiah', display_order=40,
        facility_turnover_code='peredaran_bruto',
        facility_turnover_cap=Decimal('4800') * M,
        facility_full_rate_cap=Decimal('50000') * M,
        facility_factor=Decimal('0.5'),
        components=[{'source': 'rule', 'source_rule_code': 'laba_kena_pajak',
                     'sign': 1, 'label': 'Penghasilan kena pajak'}],
        notes='Tidak berlaku bersamaan dengan PPh Final UMKM — pilih salah satu '
              'dan nonaktifkan yang lain.',
    ),
    _rule(
        'ppn_keluaran',
        name='PPN Keluaran 11%',
        description='PPN atas penyerahan barang kena pajak. Jasa kesehatan pada '
                    'umumnya dikecualikan, sehingga dasarnya hanya penjualan produk.',
        basis='period', rate_mode='flat', rate_percent=Decimal('11'),
        rounding='rupiah', display_order=50,
        components=[{'source': 'account', 'account_number': 4200000, 'sign': 1,
                     'label': 'Penjualan produk'}],
        notes='Periksa status PKP klinik dan daftar penyerahan yang dikecualikan '
              'sebelum memakai angka ini.',
    ),
    _rule(
        'ppn_masukan',
        name='PPN Masukan',
        description='PPN yang dibayar atas pembelian kena pajak.',
        basis='period', rate_mode='none', rounding='rupiah', display_order=60,
        components=[],
        notes='BELUM DIKONFIGURASI. Faktur pajak masukan belum dicatat di buku '
              'besar — tambahkan akun PPN Masukan lalu tunjuk di sini, atau isi '
              'manual sebagai komponen Nilai Tetap.',
    ),
    _rule(
        'ppn_kurang_bayar',
        name='PPN Kurang / (Lebih) Bayar',
        description='PPN Keluaran dikurangi PPN Masukan.',
        basis='period', rate_mode='none', rounding='rupiah', display_order=70,
        components=[
            {'source': 'rule', 'source_rule_code': 'ppn_keluaran', 'sign': 1,
             'label': 'PPN Keluaran'},
            {'source': 'rule', 'source_rule_code': 'ppn_masukan', 'sign': -1,
             'label': 'PPN Masukan'},
        ],
    ),
    _rule(
        'pph_21',
        name='PPh 21 Karyawan',
        description='Tarif progresif Pasal 17 atas penghasilan bruto karyawan '
                    'setahun, dikurangi PTKP.',
        basis='ytd', rate_mode='bracket', rounding='thousand', display_order=80,
        deduction_amount=PTKP_TK0,
        component_accounts=PPH21_ACCOUNTS,
        brackets=PPH21_BRACKETS,
        notes='Dihitung dari akun beban gaji secara agregat dengan PTKP TK/0. '
              'Ini pendekatan kasar: PPh 21 sebenarnya dihitung per karyawan '
              'menurut status PTKP masing-masing.',
    ),
]


class Command(BaseCommand):
    help = 'Seed the default Indonesian tax rules for the taxation page.'

    def add_arguments(self, parser):
        parser.add_argument('--dry-run', action='store_true',
                            help='Report what would change without writing.')
        parser.add_argument('--overwrite', action='store_true',
                            help='Replace rules that already exist.')

    def handle(self, *args, **options):
        dry = options['dry_run']
        overwrite = options['overwrite']

        accounts = {a.account_number: a for a in ChartOfAccounts.objects.all()}
        created, skipped, replaced, warnings = [], [], [], []

        with transaction.atomic():
            by_code = {}
            for spec in RULES:
                code = spec['code']
                existing = TaxRule.objects.filter(code=code).first()
                if existing and not overwrite:
                    skipped.append(code)
                    by_code[code] = existing
                    continue
                if existing:
                    replaced.append(code)
                    existing.components.all().delete()
                    existing.brackets.all().delete()
                    rule = existing
                else:
                    created.append(code)
                    rule = TaxRule(code=code)

                rule.name = spec['name']
                rule.description = spec.get('description', '')
                rule.basis = spec.get('basis', 'period')
                rule.rate_mode = spec.get('rate_mode', 'flat')
                rule.rate_percent = spec.get('rate_percent', Decimal('0'))
                rule.deduction_amount = spec.get('deduction_amount', Decimal('0'))
                rule.rounding = spec.get('rounding', 'rupiah')
                rule.display_order = spec.get('display_order', 0)
                rule.notes = spec.get('notes', '')
                rule.facility_turnover_cap = spec.get('facility_turnover_cap', Decimal('0'))
                rule.facility_full_rate_cap = spec.get('facility_full_rate_cap', Decimal('0'))
                rule.facility_factor = spec.get('facility_factor', Decimal('0.5'))
                turnover_code = spec.get('facility_turnover_code')
                if turnover_code:
                    rule.facility_turnover_rule = by_code.get(turnover_code)
                    if rule.facility_turnover_rule is None:
                        warnings.append(
                            f'{code}: aturan omzet "{turnover_code}" belum ada.')
                rule.save()
                by_code[code] = rule

                for i, comp in enumerate(spec.get('components', [])):
                    account = None
                    if 'account_number' in comp:
                        account = accounts.get(comp['account_number'])
                        if account is None:
                            warnings.append(
                                f"{code}: akun {comp['account_number']} tidak ada, "
                                f'komponen dilewati.')
                            continue
                    source_rule = None
                    if comp.get('source_rule_code'):
                        source_rule = by_code.get(comp['source_rule_code'])
                        if source_rule is None:
                            warnings.append(
                                f"{code}: aturan {comp['source_rule_code']} belum ada, "
                                f'komponen dilewati.')
                            continue
                    TaxRuleComponent.objects.create(
                        rule=rule,
                        source=comp['source'],
                        sign=comp.get('sign', 1),
                        account=account,
                        account_type=comp.get('account_type', ''),
                        source_rule=source_rule,
                        label=comp.get('label', ''),
                        display_order=i,
                    )

                for i, number in enumerate(spec.get('component_accounts', [])):
                    account = accounts.get(number)
                    if account is None:
                        warnings.append(f'{code}: akun {number} tidak ada, dilewati.')
                        continue
                    TaxRuleComponent.objects.create(
                        rule=rule, source='account', sign=1, account=account,
                        label=f'{account.account_number} – {account.name}',
                        display_order=i,
                    )

                for i, (upper, rate) in enumerate(spec.get('brackets', [])):
                    TaxRuleBracket.objects.create(
                        rule=rule, upper_bound=upper, rate_percent=rate,
                        display_order=i,
                    )

            if dry:
                transaction.set_rollback(True)

        for code in created:
            self.stdout.write(self.style.SUCCESS(f'  + {code}'))
        for code in replaced:
            self.stdout.write(self.style.WARNING(f'  ~ {code} (diganti)'))
        for code in skipped:
            self.stdout.write(f'  = {code} (sudah ada, dilewati)')
        for warning in warnings:
            self.stdout.write(self.style.WARNING(f'  ! {warning}'))

        verb = 'akan dibuat' if dry else 'dibuat'
        self.stdout.write(self.style.SUCCESS(
            f'\n{len(created)} aturan {verb}, {len(replaced)} diganti, '
            f'{len(skipped)} dilewati.'))
        if dry:
            self.stdout.write(self.style.WARNING('DRY RUN — tidak ada yang disimpan.'))
